server:
  port: 8081

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthenticationFilter
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/projects/**
          filters:
            - name: AuthenticationFilter
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG