spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: ""
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/task-manager
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/task-manager

logging:
  level:
    org.springframework.security: DEBUG