# Общие настройки для всех сервисов
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    config:
      enabled: true

logging:
  level:
    com.example: INFO
    org.springframework.cloud: INFO