server:
  port: 8761

spring:
  application:
    name: service-discovery

# САМОЕ ВАЖНОЕ - отключаем регистрацию Eureka клиента
eureka:
  client:
    register-with-eureka: false    # Не регистрироваться в Eureka
    fetch-registry: false          # Не получать реестр сервисов
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info