server:
  port: 8084

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    com.example.taskservice.client: DEBUG